"""Module with basic constants."""

METHOD_POST = "POST"
METHOD_GET = "GET"
METHOD_HEAD = "HEAD"
METHOD_OPTION = "OPTION"

SUPPORTED_METHODS = (
    METHOD_POST,
    METHOD_GET,
    METHOD_HEAD,
    METHOD_OPTION,
)

MAX_URL_LENGTH = 2083

HTTP_SCHEMA = "http://"
HTTPS_SCHEMA = "https://"

SUPPORTED_SCHEMAS = (
    HTTP_SCHEMA,
    HTTPS_SCHEMA,
)

MIN_HEALTHCHECK_INTERVAL_SECONDS = 5
MAX_HEALTHCHECK_INTERVAL_SECONDS = 300

DEFAULT_REQUEST_INTERVAL_SECONDS = 5
DEFAULT_REQUEST_TIMEOUT_SECONDS = 15

DEFAULT_CONFIG_FILENAME = "monitoring-config"
DEFAULT_LOCALDB_FILENAME = "local-database.sqlite3"
DEFAULT_CONFIG_PATH = f"~/.monitoring/{DEFAULT_CONFIG_FILENAME}"
DEFAULT_LOCALDB_PATH = f"~/.monitoring/{DEFAULT_LOCALDB_FILENAME}"

DEFAULT_VERBOSITY_LEVEL = 0
DEBUG_LEVEL = 5
INFO_LEVEL = 4
WARNING_LEVEL = 3
ERROR_LEVEL = 2

LOGGING_VERBOSITY_LEVELS = (
    DEBUG_LEVEL,
    INFO_LEVEL,
    WARNING_LEVEL,
    ERROR_LEVEL,
)
MINUTE_SECONDS = 60
SYSTEMD_SOCKET = "/run/systemd/notify"
SYSTEMD_NOTIFY_MESSAGE = b"READY=1"
DEFAULT_HEADERS = {"user-agent": "monitoring-client"}
